import { Inter } from "next/font/google";
import "./global.css";
import NavBar from "../components/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Learning App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NavBar />
      <body>{children}</body>
    </html>
  );
}
